#%RAML 1.0 NamedExample
value:
  name: GenePoint
  age: '35'
  gender: Male
  type: Account
  billingCountry: USA
  billingStreet: '345 Shoreline Park'
  billingCity: Mountain View
  phone: '(650) 867-3450'
  billingPostalCode: '75251'
  Id: 0015i0000089pHEAAY